---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: web
  name: web
  namespace: devtest2020
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.podinfod: semver:~1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: web
    spec:
      containers:
      - image: bitnami/nginx:1.19
        name: hello-app
        resources: {}
status: {}
